#
# DESPLIEGUE DE MICROSERVICIOS "FIT OR FAT"
#
# Definición del espacio de nombre
kind: Namespace
apiVersion: v1
metadata:
  name: fitorfat
---
# Despliegue del microservicio HU-16 e HU-17 CORE "Retar a un amigo"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hu16y17-desp
  namespace: fitorfat
  labels:
    app: hu16y17
spec:
  selector:
    matchLabels:
      app: hu16y17
  replicas: 3
  template:
    metadata:
      labels:
        app: hu16y17
    spec:
      containers:
      - name: hu16y17
        image: fitorfatacr.azurecr.io/hu16y17:latest
        ports:
        - containerPort: 80
---
# Servicio "ClusterIP" para poder acceder al microservicio HU-16 e HU-17 CORE
apiVersion: v1
kind: Service
metadata:
    name: hu16y17-serv
    namespace: fitorfat
spec:
    selector:
      app: hu16y17
    type: ClusterIP
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
